import requests
from bs4 import BeautifulSoup
import re
url = "https://www.imdb.com/title/tt0073195/?ref_=nv_sr_srsg_0" #voy sustituyendo en la url el id que he sacado en el archivo con la funcion
#funcion clave_id del archivo funcion_id  y me va dando el lugar donde se encuentra el rating, lo mismo que con las actrices.. Funciona en todos por igual.

rating = requests.get(url).text

soup = BeautifulSoup(rating, "html.parser")
ratings= soup.find_all("strong", title= True)

print(ratings)

print("-----------------------------------------------------------")
#EL ejemplo usado aquí, es el de la pelicula jaws, pero se puede poner en el url , el id que quieras.
#Aqui sacamos todos los ratings, para pasarlos posteriormente a la tabla.
"""{'2001: A Space Odyssey':8.3,
 '8 1/2': 0,
 'A Clockwork Orange': 8.3,
 'A Fistful of Dollars': 8,
 'After Hours': 7.7,
 'Aliens': 8.3,
 'Amarcord': 7.9,
 'Apocalypse Now':8.4,
 'Arrowsmith': 6.2,
 'Battle of Midway The':7.5,
 'Bellboy & the Playgirls The':3.1,
 'Bird':7.1,
 'Bonfire of the Vanities The': 5.6,
 'Bronco Billy' : 6.1,
 'Cape Fear':7.3,
 'Color of Money The':7,
 'Conversation The':7.8,
 "Donovan's Reef":6.9,
 'Duel':7.6,
 'E. T. The Extra-Terrestrial':7.8,
 'Eiger Sanction The':6.4,
 'El Guerrero Solitario':6.9,
 'Empire of the Sun':7.7,
 'Fellini Satyricon':6.9,
 'Firefox':6,
 'For a Few Dollars More':8.3,
 'Fort Apache':7.5,
 'Full Metal Jacket':8.3,
 'Gardens of Stone':6.4,
 'Gauntlet The':6.4,
 'Ginger & Fred':7.3,
 'Godfather The':9.2,
 'Good Fellas':8.7,
 'Heartbreak Ridge':6.9,
 'High Heels':7.1,
 'High Plains Drifter':7.5,
 'Honkytonk Man':6.6,
 'Hook':6.8,
 'Horse Soldiers The':7.2,
 'Il Bidone':7.5,
 'Indiana Jones & the Last Crusade':8.2,
 'Jaws':8,
 'Judge Priest':6.3,
 "Killer's Kiss":6.6,
 'Killing The':8,
 'King of Comedy':7.8,
 'La Dolce Vita':8,
 'Last Hurrah The':7.4,
 'Last Temptation of Christ The':7.5,
 'Law of Desire':7.1,
 'Lolita':7.6,
 'Long Gray Line The':7.2,
 'Long Voyage Home The':7,
 'Man Who Shot Liberty Valance The':8.1,
 'Matador':7,
 'Mister Roberts':7.7,
 'Mogambo':6.7,
 'My Darling Clementine':7.8,
 'New York New York':6.7,
 'New York Stories':6.4,
 'Night Gallery':8,
 'Nineteen Forty-One':7.2,
 'Outsiders The':7.1,
 'Pale Rider':7.3,
 'Paths of Glory':8.4,
 'Peggy Sue Got Married':6.3,
 'People The':6.3,
 'Pepi Luci Bom':6.2,
 'Pink Cadillac':5.4,
 'Play Misty for Me':7,
 'Raging Bull':8.2,
 'Raiders of the Lost Ark':8.4,
 'Rain People The':6.9,
 'Rio Grande':7.1,
 'Roma':8.7,
 'Rookie THe':5.9,
 'Rumble Fish':7.2,
 'Searchers The':7.9,
 'She Wore a Yellow Ribbon':7.3,
 'Shining The':8.4,
 'Spartacus':7.9,
 'Sugarland Express The':6.8,
 'Sun Shines Bright The':7,
 'Terminator 2':8.5,
 'Terminator The':8,
 'They Were Expendable':7.2,
 'Three Godfathers':7.1,
 'Tie Me Up! Tie Me Down!':7,
 'Tonight for Sure':3.1,
 'Tucker: The Man & His Dream':6.9,
 'Untouchables The':7.9,
 'Wagon Master':7.1,
 'Wagonmaster':7.1,
 'Wee Willie Winkie':7.1,
 'What Price Glory?': 6.3,
 'White Hunter Black Heart':6.6,
 'Wings of Eagles The':6.7,
 'Wise Guys':5.7,
 'Women on the Verge of a Nervous Breakdown':7.6}
 """